### ISSUE TITLE
DateTime vs DateTimeImmutable

### ISSUE THREAD

**Issue by nyamsprod** [delight-im/PHP-Temporal#2]
@ocram  This is a question more than an Issue. Why do you use internally a `DateTime` object instead of a `DateTimeImmutable` object. The later would I believe remove any `clone` usage in your codebase, unless I'm missing something ?

**Comment by ocram** [comment]
@nyamsprod It's just that this library has full control over when to create a copy and when to re-use the existing instance. You're probably right and `DateTimeImmutable` would fit perfectly, replacing all occurrences where a copy is currently made. The switch could be made, but I don't see great advantages, neither in readability nor in maintainability.

If, however, making the switch would introduce significant performance improvements, this should definitely be considered.

**Comment by ocram** [comment]
By the way, *not* using `DateTimeImmutable` *internally* allows us to do something like this, for example:

```php
public function subAndRoundToDays(DateInterval $interval) {
    $copy = $this->copy();

    $copy->sub($interval);
    $copy->setTime(0, 0, 0);

    return $copy;
}
```

This example is contrived, but the general concept is not. Using `DateTimeImmutable` internally would cause another copy here.

**Comment by nyamsprod** [comment]
Let's break your example.
```php 
$copy : $this->copy();
// is equivalent to 
$copy = clone $this;
```
First, you are creating a public method for something PHP already does which feels strange unless your `Temporal::copy` method does something else extra you can not do with the `clone` keyword ? 

Second I believe your `$copy` variable refers to the internal `$dateTime` variable as no `Temporal::sub` method exists. That put aside, making it an `DateTimeImmutable` renders your code more Human readable and thus maintainable since the whole premise is that `Temporal` is immutable to begin with.

```php
public function subAndRoundToDays(DateInterval $interval) {
   return new self(
      $this->dateTime->sub($interval)->setTime(0, 0, 0)
   );
}
```
Third, if you are so worry about performance making clones or copy in PHP using `DateTimeImmutable` is cheap, the overhead for creating your class is minimal since your class only contains one property.
  
Last but not least, the large diff is a mistake from my part because my IDE is configure to convert code in PSR-2 style, I've updated the PR so ignore formatting the code .. you'll see that the diff is much smaller this way :)

Hope I've answered your question

**Comment by ocram** [comment]
> First, you are creating a public method for something PHP already does which feels strange

No, that's not what it is. Obviously, I wouldn't create a method that just executes *one* other statement, unless there are some advantages. This here is purely for the interface. It allows for easier chaining, at virtually no cost.

> Second I believe your `$copy` variable refers to the internal `$dateTime` variable as no `Temporal::sub` method exists

Yes, of course. Sorry, that was just contrived and written quickly for that response.

> That put aside, making it an `DateTimeImmutable` renders your code more Human readable and thus maintainable

I'm afraid one can certainly argue about this. One could even say that creating the copies explicitly is easier to read because you *see* where immutability "happens". Otherwise, the way that immutability is enforced is somewhat hidden.

> since the whole premise is that `Temporal` is immutable to begin with

Yes, and that has always been both enforced and easily visible with the current code.

> Third, if you are so worry about performance making clones or copy in PHP using `DateTimeImmutable` is cheap, the overhead for creating your class is minimal since your class only contains one property.

Yes, I know. It's the same thing we're already doing. In both the current code and in your proposal, a new instance of the `Temporal` class is being created whenever an instance is "modified". In addition, the current code creates a copy of the internal `DateTime` instance in all these cases, while your proposal just lets `DateTimeImmutable` create that copy itself.

> Last but not least, the large diff is a mistake from my part because my IDE is configure to convert code in PSR-2 style, I've updated the PR so ignore formatting the code .. you'll see that the diff is much smaller this way :)

I see, thanks! Much better now :)

All in all, I'm not really against this change. I just don't think it's that much of an improvement. Anyway, we could certainly do it. Let's just track the implementation in the pull request.
